# Basic
hard_tabs = true
max_width = 100
use_small_heuristics = "Max"
# Imports
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
# Consistency
newline_style = "Unix"
# Format comments
comment_width = 100
wrap_comments = true
# Misc
binop_separator = "Back"
chain_width = 80
match_arm_blocks = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
reorder_impl_items = true
spaces_around_ranges = false
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true

